version: "3.9"
services:
  database:
    image: "mysql:8.0.32"
    container_name: mysql
    ports:
      - "3306:3306" 
    volumes:
      - datafiles:/var/lib/mysql,
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_USER: ceohelperdevuser
      MYSQL_PASSWORD: Qwe1234!
      MYSQL_DATABASE: ceohelperdev
  ceohelperdev:
    image: ceohelperdev:runtime
    depends_on: 
      - database
    build:
       context: .
       dockerfile: CeoHelper\Dockerfile
    ports:
      - "8080:5000"
    restart: always
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
    datafiles: